This is the source code for the abs-models.org website.  It is built using
[[https://gohugo.io/][Hugo]] and deployed via the ~deploy.sh~ script in this directory.

We recommend ~git config submodule.recurse true~ so that ~git pull~
automatically updates the ~public/~ submodule; otherwise, run ~git submodule
update~ after ~git pull~.

The ~static/manual/~ subdirectory is updated manually for each release of the
basic tools.  See https://github.com/abstools/abstools/blob/master/RELEASE.md
for instructions.

The files in https://github.com/abstools/absexamples/tree/master/collaboratory
are installed in the collaboratory and can be linked from tutorials in this
site.

To create a link that opens such a file in the collaboratory, use the
~eifilelink~ shortcode, which opens the specified file in the collaboratory in
a new tab.  The ~eifilelink~ shortcode comes in two variants, with positional
and named parameters.

With positional parameters, the first parameter gives the relative url of the
file and the second parameter the link text.  If an app is to be specified,
append it to the relative url.
#+BEGIN_SRC
{{< eifilelink "/collaboratory/hello_world.abs&app=cost" "hello_world.abs" >}}
#+END_SRC

With named parameters, the ~path~ parameter gives the relative path.  The
~title~ parameter gives the link text; it is set to the filename if omitted.
The ~app~ parameter gives the app to select; it can be omitted.
#+BEGIN_SRC
{{< eifilelink path="/collaboratory/hello_world.abs" app="cost" title="The hello world example" >}}
#+END_SRC
