== Real-Time ABS

In order to run timed simulations, which forms the basis of simulations
estimating the effect of different resource usage and deployment scenarios, it
is necessary to introduce a notion of time into the language.

The ABS notion of time is _dense time_ with _run-to-completion semantics_.
This means that in a simulation, statements run infinitely fast. Time advances
when all processes meet one of the following conditions:

* the cog of the process is blocked
* the process is suspended waiting for time to advance
* the process is waiting for a resource to become available
* the process is suspended or blocked waiting for another process

In practice this means that all process run as long as there is "work to be
done."  Once all processes are stuck waiting (directly or indirectly) for the
clock, the clock advances by an amount sufficient to unblock at least one
process (big-step time advance semantics).

NOTE: An ABS model that contains neither duration nor resource constructs will
run without influencing the clock.  This means that all ABS models are valid
in Real-Time ABS; Real-Time ABS is a strict super-set of ABS.

=== Language constructs for expressing time in ABS

The standard library contains the following definition of a time datatype:

----
data Time = Time(Rat timeValue);
def Time now() = ...
----

The function `now` always returns the current time.

The following constructs cause time to advance:

.Syntax
----
duration(Rat min, Rat max);
await duration(Rat min, Rat max);
----

The `duration` statement blocks the cog of the executing process until at
least `min` and at most `max` time units have passed.  The `await duration`
statement suspends the current process until at least `min` and at most `max`
time units have passed.

The difference between `duration` and `await duration` is that in the latter
case other processes in the same cog can execute while the awaiting process is
suspended.  In the case of the blocking `duration` statement, no other process
in the same cog can execute.  Note that processes in other cogs are not
influenced by `duration` or `await duration`, except when they attempt to
synchronize with that process.

WARNING: A subtle difference between `duration` and `await duration` is that in
the latter case, the suspended process becomes eligible for scheduling after
the specified time, but there is no guarantee that it will actually be
scheduled at that point.  This means that more time might pass than expressed in the `await duration` guard!

.Examples

----
  Time t = now();
  await duration(1/2, 5); <1>
  Time t2 = now(); <2>
----
<1> Here the *process* suspends for 1/2-5 time units
<2> `t2` will be at least 1/2 time units larger than `t`

----
  Time t = now();
  duration(1/2, 5); <1>
  Time t2 = now(); <2>
----
<1> Here the *cog* blocks for 1/2-5 time units
<2> `t2` will be between 1/2 and 5 time units larger than `t`

