#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
CODEPATHS=$(find "$SCRIPTPATH" -name "ebin" -type d -print0 \
                 | xargs -0 printf '%s","' | sed 's/","$//g')

TMPFILE=$(mktemp)

cat << EOF > "$TMPFILE"
#!/usr/bin/env escript
% use this to increase process limit: %%! +P 134217727
main(Arg)->
code:add_paths(["$CODEPATHS"]),
runtime:run(Arg).
EOF

cleanup () {
    rm "$TMPFILE" &> /dev/null
    return $exit_code
}

trap cleanup EXIT
escript "$TMPFILE" "$@"
exit_code=$?
