#!/bin/bash
set -e

scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
codepaths=$(find "$scriptpath" -name "ebin" -type d -print0 \
                 | xargs -0 printf '%s","' | sed 's/","$//g')

(cd $scriptpath/absmodel && ../bin/rebar compile)

(
    echo "code:add_paths([\"$codepaths\"])."
    echo "runtime:start(\"$@\")."
    cat
) | erl
