#!/bin/bash

PROGNAME="$(readlink $0)"
if [[ -z $PROGNAME ]] ; then
    PROGNAME="$0"
fi
BASEDIR="$(dirname $PROGNAME)/../.."

if [[ $1 == "-haskell" ]]; then
    if command -v abs2haskell > /dev/null; then # is in the PATH
       args=${@#-haskell} # remove -haskell from the rest of params
       mkdir gen/haskell 2> /dev/null || true # will continue if it is already there
       absc -prettyprint $args > /dev/null && abs2haskell --outputdir=gen/haskell $args # typecheck all ABS files and if succeed then continue to abs2haskell translation
       echo -e '#!/usr/bin/env bash\nif [[ $# -eq 0 ]]; then echo "USAGE: You have to provide the name of the main module"; exit 1; else ghc -w --make -O -threaded ${1}.hs ${@:2} -main-is $1 -o run && echo "Compiled. Run the program with ./run"; fi' > gen/haskell/compile_main_module
       chmod +x gen/haskell/compile_main_module
    else
       echo "Error: The abs2haskell compiler is not installed or not in the $PATH."
       exit 1
    fi
else
    java -Xmx512m -cp $BASEDIR/dist/absfrontend.jar abs.frontend.parser.Main "$@"
fi
