#!/bin/bash

PROGNAME="$(readlink $0)"
if [[ -z $PROGNAME ]] ; then
    PROGNAME="$0"
fi
BASEDIR="$(dirname $PROGNAME)/../.."

java -Xmx512m -cp $BASEDIR/dist/absfrontend.jar abs.frontend.parser.Main "$@"
