#!/bin/bash

PROGNAME="$(readlink $0)"
if [[ -z $PROGNAME ]] ; then
    PROGNAME="$0"
fi
BASEDIR="$(dirname $PROGNAME)/../.."

java -cp $BASEDIR/bin:$1 -Dabs.debug=true -Dabs.loglevel=finest -Dabs.systemobserver=abs.backend.java.debugging.GraphicalDebugger -Dabs.totalscheduler=abs.backend.java.scheduling.InteractiveScheduler $2.Main


