#!/bin/bash

PROGNAME="$(readlink $0)"
if [[ -z $PROGNAME ]] ; then
    PROGNAME="$0"
fi
BASEDIR="$(dirname $PROGNAME)/../.."

java -cp $BASEDIR/bin:$BASEDIR/lib/beaver-rt-src.jar:$BASEDIR/lib/beaver-rt.jar:$BASEDIR/lib/org.sat4j.core.jar:$BASEDIR/lib/org.sat4j.pb.jar:$BASEDIR/lib/sat4j-pb.jar:$BASEDIR/lib/org.sat4j.maxsat.jar:$BASEDIR/lib/sat4j-maxsat.jar:$BASEDIR/lib/choco-solver-2.1.1.jar abs.backend.maude.MaudeCompiler "$@"


