#!/bin/bash

# Rudi Schlatte May 2010, based on parseABS by Arild Torjusen April 2010


BASEDIR="@BASEDIR@" 

function usage
{
    echo "Usage: `basename $0` absfile"
    echo
}

function help
{
    echo `basename $0`
    echo
    echo "A preliminary version of an ABS compiler."
    usage;
    echo 'Legal options: '
    echo '-h : Display help'
    exit 0
}
echo

while getopts ":ho:v" Option
do
  case $Option in
    h ) help;; 
    o ) outfile=$OPTARG;;
    * ) echo "Illegal option: $1";usage;exit 1;;      
  esac
done
shift $(($OPTIND - 1))

if [ "$outfile" == "" ] ; then
    outfile=${1%.*}.maude
fi

if [ -n "$1" ] ; then 
    eval java -cp $BASEDIR/lib/beaver-rt.jar:$BASEDIR/bin abs.frontend.tests.GenerateMaudeTest $1 > $outfile
else
    echo 'No file specified.'
    usage;
    exit 2
fi
exit 0


