#!/bin/bash

PROGNAME="$(readlink $0)"
if [[ -z $PROGNAME ]] ; then
    PROGNAME="$0"
fi
BASEDIR="$(dirname $PROGNAME)/../.."
CP=$BASEDIR/bin:$BASEDIR/lib/*

#echo $CP

java -Xmx512m -cp gen:$CP "$@"
