/** 
 * Copyright (c) 2009-2011, The HATS Consortium. All rights reserved. 
 * This file is licensed under the terms of the Modified BSD License.
 */
package abs.backend.prettyprint;

import java.io.PrintWriter;

/**
 * The ABS formatter is responsible for changing the look
 * of source code, generated by the PrettyPrint aspect
 * 
 * @author Jan Schäfer
 *
 */
public interface ABSFormatter {
    void setPrintWriter(PrintWriter w);
    
    void beforeOpenBrace();
    void afterOpenBrace();
    void afterStmt();
    void beforeCloseBrace();
    void afterCloseBrace();
    
}
