package abs.frontend.tests;

import java.io.PrintWriter;

/**
 * The ABS formatter is responsible for changing the look
 * of source code, generated by the PrettyPrint aspect
 * 
 * @author Jan Schäfer
 *
 */
public interface ABSFormatter {
    void setPrintWriter(PrintWriter w);
    
    void beforeOpenBrace();
    void afterOpenBrace();
    void afterStmt();
    void beforeCloseBrace();
    void afterCloseBrace();
    
}
