/*
 * generated by Xtext 2.18.0
 */
package org.abs_models.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.abs_models.xtext.AbsRuntimeModule;
import org.abs_models.xtext.AbsStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AbsIdeSetup extends AbsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AbsRuntimeModule(), new AbsIdeModule()));
	}
	
}
