/*
 * generated by Xtext 2.17.0.M1
 */
package org.abs_models.xtext.ide

import com.google.inject.Guice
import org.abs_models.xtext.AbsRuntimeModule
import org.abs_models.xtext.AbsStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AbsIdeSetup extends AbsStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AbsRuntimeModule, new AbsIdeModule))
	}
	
}
