/*
 * generated by Xtext 2.18.0
 */
package org.abs_models.xtext.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AbsScopeProvider extends AbstractAbsScopeProvider {

    @Override
    public IScope getScope(EObject context, EReference reference) {
        return super.getScope(context, reference);
    }

}
