%%% Compile behaviours first...

%%% Compile the rest of the code...
{ 
    [
    "./runtime/src/task.erl",
    "./runtime/src/object.erl",
    "./*",
    "./runtime/lib/*",
	"./runtime/src/*"
    ], 
    [
	{ i, "./runtime/include" },
    { i, "./ebin" },
    {source,"./ebin"},
    { outdir, "./ebin" },
    debug_info,
	nowarn_unused_vars,
	nowarn_unused_function,
	nowarn_shadow_vars,
	nowarn_export_all
    ]
}.
