== Functions

Functions in ABS define names for parametrized data expressions. A Function in ABS is always side effect-free, which means that it cannot manipulate the heap.

.Syntax

[source,java]

----
def Int length(IntList list) =
case list {
	Nil => 0;
	Cons(n, ls) => 1 + length(ls);
};
----

.Parametric Functions

Parametric Functions allow to work with parametric data types in a general way. For exam-
ple, given a list of any type, a parametric function head can return the first element, regardless
of its type. Parametric functions are defined like normal functions but have an additional type
parameter section inside angle brackets (< >) after the function name.

.Syntax

----
def A head<A>(List<A> list) =
	case list {
	Cons(x, xs) => x;
};

----

.N-ary Constructors
For data types of arbitrary size, like lists, maps and sets, it is undesirable having to write them down in the form of nested constructor expressions. For this purpose, ABS provides a special syntax for nary constructors, which are transformed into constructor expressions via a user-supplied function. 

.Syntax
[source,java]

----
def Set<A> set<A>(List<A> l) = case l {
    Nil => EmptySet;
    Cons(hd, tl) => Insert(hd, set(tl));
    };

{
Set<Int> s = set[1, 2, 3];
}
----

