== Pure Expressions

Pure Expressions are side effect-free expressions. This means that these expressions cannot modify the heap.

.Let Expressions

These expressions bind variable names to pure expressions.

.Syntax

[source]

----
let (Bool x) = True in !x
----
.Data Type Constructor Expressions

They are expressions that create data type values by using data type constructors. Note that for data type constructors that have no parameters, the parentheses are optional.

.Syntax

[source]

----
True
Cons(True, Nil)
ABS.StdLib.Nil
----

.Function Applications

Function Applications apply functions to arguments.

.Syntax

[source]

----
tail(Cons(True, Nil))
ABS.StdLib.head(list)
----

.If-Then-Else Expression

ABS has a standard if-then-else expression.

.Syntax

[source]

----
if 5 == 4 then True else False
----

.Case Expressions / Pattern Matching

ABS supports pattern matching by the Case Expression. It takes an expression as first argument, which a series of patterns is matched against. The value of the case expression itself is the value of the expression on the right-hand side of the first matching expression. It is an error if no pattern matches the expression.

=== Patterns

There are five different kinds of patterns available in ABS:

* Pattern Variables (e.g., x, where x is not bound yet)
* Bound Variables (e.g., x, where x is bound)
* Literal Patterns (e.g., 5)
* Data Constructor Patterns (e.g., Cons(Nil,x))
* Underscore Pattern (_)

.Pattern Variables

Pattern variables are simply unbound variables. Like the underscore pattern, these variables match every value, but, in addition, bind the variable to the matched value. The bound variable can then be used in the right-hand-side expression of the corresponding branch. Typically, pattern variables are used inside of data constructor patterns to extract values from data constructors. For example 

[source]
----
def A fromJust<A>(Maybe<A> a) =
case a {
	Just(x) => x;
};

----

.Bound Variables

If a bound variable is used as a pattern, the pattern matches if the value of the case expression is equal to the value of the bound variable.

[source]
----
def Bool contains<A>(List<A> list, A value) =
case list {
	Nil => False;
	Cons(value, _) => True;
	Cons(_, rest) => contains(rest, value);
};

----

.Literal Patterns
Literals can be used as patterns. This is similar to bound variables, because the pattern matches if the value of the case expression is equal to the literal value.

[source]
----
def Bool isEmpty(String s) =
case b {
	"" => True;
	_ => False;
};

----

.Data Constructor Patterns
A data constructor pattern is like a standard data constructor expression, but where certain sub expressions can be patterns again.


[source]
----
def Bool negate(Bool b) =
case b {
	True => False;
	False => True;
};

----

[source]
----
def List<A> remainder(List<A> list) =
case b {
	Cons(_, rest) => rest;
};

----

.Underscore Pattern
The underscore pattern (_) simply matches every value. It is generally used as the last pattern in a case expression to define a default case. For example:

[source]
----
def Bool isNil<A>(List<A> list) =
case list {
	Nil => True;
	_ => False;
};
----

=== Type Checking

A case expression is type-correct if and only if all its expressions and all its branches are type-correct and the right-hand side of all branches have a common super type. This common super type is also the type of the overall case expression. A branch (a pattern and its expression) is type-correct if its pattern and its right-hand side expression are type-correct. A pattern is type-correct if it can match the corresponding case ex-pression.

.Operator Expressions
ABS has a number of predefined operators which can be used to form Operator Expressions.

The following table describes the meaning as well as the associativity and the precedence of the different operators. They are grouped according to precedence, as indicated by horizontal rules, from low precedence to high precedence.

[options="header,footer"]
|=======================
|Expression|Meaning      |Associativity |Argument types |Result type
|e1 \|\| e2 |logical or |left |Bool, Bool |Bool
|e1 && e2 |logical and |left |Bool, Bool |Bool
|e1 == e2 |equality |left |compatible |Bool
|e1 != e2 |inequality |left |compatible |Bool
|e1 < e2 |less than |left |compatible |Bool
|e1 <= e2 |less than or equal to |left |compatible |Bool
|e1 > e2 |greater than |left |compatible |Bool
|e1 >= e2 |greater than or equal to |left |compatible |Bool
|e1 + e2 |concatenation |left |String, String |String
|e1 + e2 |addition |left |number, number |number
|e1 - e2 |subtraction |left |number, number |number
|e1 * e2 |multiplication |left |number, number |number
|e1 / e2 |division |left |number, number |Rat
|e1 % e2 |modulo |left |number, number |Int
|! e |logical negation |right |Bool |Bool
|- e |integer negation |right |number |number
|=======================
