= Imperative Sublanguage

== Control Statements

Similar to Java, a  statement is each of the individual instructions of a program, like the variable declarations and expressions seen in previous sections. They always end with a semicolon (;), and are executed in the same order in which they appear in a program. ABS provides flow control statements that serve to specify what has to be done by our program, when, and under which circumstances. Statements in ABS are not evaluated to a value. If one wants to assign a value to statements it would be the *Unit* value.

.Block

This statement is also known as a *compound statement* and consists of a group of statement grouped together defining a name scope for variables. 


[source]
----
{
	a = a + 1;
	n = n % 10;
}
----

.Selection statement


[source, java]
----
if (5 < x) {
	y = 6;
} 
else {
	y = 7;
}
if (True)
	x = 5;


----

.Iteration statement (Loop)


[source, java]
----
while (x < 5)
	x = x + 1;
----

.Variable Declaration Statements

A variable declaration statement is used to declare variables. A variable has an optional initialization expression for defining the initial value of the variable. The initialization expression is mandatory for variables of data types. It can be left out only for variables of reference types, in which case the variable is initialized with null. 

[source, java]
----
Bool b = True;
----

.Assign Statement 

The *Assign Statement* assigns a value to a variable or a field.


[source, java]
----
this.f = True;
x = 5;
----


.Await Statement

*Await Statements* suspend the current task until the given guard is true [7]. The task will not be suspended if the guard is already initially true. While the task is suspended, other tasks within the same COG can be activated. Await statements are also called scheduling points, because they are the only source positions, where a task may become suspended and other tasks of the same COG can be activated.


[source, java]
----
Fut<Bool> f = x!m();
await f?;
await this.x == True;
await f? & this.y > 5;
----

.Suspend Statement

A Suspend Statement causes the current task to be suspended.

[source, java]
----
suspend;
----

.Assert Statement

An *Assert Statement* is a statement for asserting certain conditions.

[source, java]
----
assert x != null;
----

.Return Statement

A *Return Statement* defines the return value of a method. A return statement can only appear as a last statement in a method body.

[source, java]
----
return x;
----

.Case Statement

The case statement, like the case expression, takes an expression as first argument, which is
matched against a series of patterns. The effect of executing the case statement is the execution of
the statement (which can be a block) of the first branch whose pattern matches the expression. An example
follows:

[source, java]

----
Pair<Int, Int> p = Pair(2, 3);
Int x = 0;
case p {
  Pair(2, y) => { x = y; skip; }
  _ => x = -1;
}
----

.Exception-signaling statement

The keyword-statement `throw` is used to signal exceptions (runtime errors).
It takes a single argument which is the exception-value to throw. For example:

[source, java]

----
{
 Int x = -1;
 if (x<0) {
    throw NegativeNumberException(x);
 }
 else {
   if (x==0) {
      throw ZeroNumberException;
   }
   else ...
}
----

[NOTE]
The 'throw' statement can only be used inside imperative code.
Throwing user-exceptions inside functional code is considered bad practice:
the user's function must be written instead to return an +Either<Exception, A>+ value,
as in the example:

----
def Either<Exception, Int> f(x,y) = if (y < 0)
                                    then Left(NegativeNumberException)
                                    else Right(...)
----

Despite this, there are certain built-in system-exceptions (see Section 3.3) that can originate
from erroneous functional code. Examples of these are
`DivisionByZeroException` and `PatternMatchFailException`, implicitly signaled
by the ABS system.

When an exception is raised (signaled), the normal flow of the program will be abrupted. In order to resume
the normal flow, the user has to explicitly *handle* the exception.

.Exception-handling Statement

To handle an exception --- either explicitly signaled using the `throw` keyword or implicitly by a system exception ---
the user has to surround the offending code with a `try` block.
The statements in the try block will be executed in sequence until an exception happens.
Upon an exception, the execution of the try block will stop and the exception will be matched against the exception-patterns
defined in the `catch` block.

The catch block behaves similar to the `case statement`, with the only difference that the patterns
can only have the type `Exception`. When the exception-pattern is matched, the statements
associated with its catch clause will be executed. 

After defining the catch block, the user can _optionally_ supply a `finally` block
of statements, that will be executed regardless of an exception happening or not.

The syntax is the following:

[source]
----
try {
 stmt1;
 stmt2;
 ....
}
catch {
  exception_pattern1  => stmt_or_block;
  exception_pattern2  => ... ;
  ...
  _ => ...
}
finally {
  stmt3;
  stmt4;
}
----

If there are no matching catch-clauses,
the finally block will first be accordingly executed,
before re-throwing the exception to its parent caller.
Conversely, if the parent caller does not (correctly) handle the re-thrown exception,
the exception will be propagated to its own parent caller, and so forth and so on.

.Expression Statement

An *Expression Statement* is a statement that only consists of a single expression. Such statements are only executed for the effect of the expression.

[source, java]
----
new C(x);

----

== Expressions with Side Effects

Beside pure expressions, ABS has expressions with side effects. However, these expressions are defined in such a way that they can only have a single side effect. This means that subexpressions of expressions can only be pure expressions again. This restriction simplifies the reasoning about ABS expressions.

.New Expression

A New Expression creates a new object from a class name and a list of arguments. In ABS objects
can be created in two different ways. Either they are created in the current COG, using the standard
new local expression, or they are created in a new COG by using the new expression.

.Syntax

[source]
----
new local Foo(5)
new Bar()
----

Standard Object Creation

When using the new local expression, the new object is created in the current COG, i.e., the COG of the current receiver object.

.COG Object Creation

The concurrency model of ABS is based on the notion of COGs [?]. An ABS system at runtime is a set of concurrently running COGs. A COGs can be seen as an isolated subsystem, which has its own state (an object-heap) and its own internal behavior. COGs are created implicitly when creating a new object by using the new expression.

.Synchronous Call Expression
A Synchronous Call consists of a target expression, a method name, and a list of argument expressions.

[source]
----
Bool b = x.m(5);
----

.Asynchronous Call Expression
An Asynchronous Call consists of a target expression, a method name, and a list of argument expressions. Instead of directly invoking the method, an asynchronous method call creates a new task in the target COG, which is executed asynchronously. This means that the calling task proceeds independently after the call, without waiting for the result. The result of an asynchronous method call is a future (Fut<V>), which can be used by the calling task to later obtain the result of the method call. That future is resolved by the task that has been created in the target COG to execute the method.

[source, java]
----
Fut<Bool> f = x!m(5);
----

.Get Expression
A Get Expression is used to obtain the value from a future. The current task is blocked until the value of the future is available, i.e., until the future has been resolved. No other task in the COG can be activated in the meantime.

[source]
----
Bool b = f.get;
----

.Await Expression
A common pattern for asynchronous calls is:

* Execute an asynchronous call expression, store the future in a variable
* `await` on the future
* Assign the result to a variable

[source]
----
Fut<A> fx = o!m();
await fx?;
A x = fx.get;
----

The await expression is a shorthand for this pattern. The preceding example can be written as follows, without the need to introduce a name for the future:

[source]
----
A x = await o!m();
----


