== Interfaces


Interfaces in ABS are similar to interfaces in Java.  They have a name, which
defines a nominal type, and they can extend zero or more other
interfaces.  The interface body consists of a list of method signature
declarations.  Method names start with a lowercase letter.

[caption=]
.Syntax
====
_InterfaceDecl_ ::= `interface` _TypeIdentifier_ [ `extends` _InterfaceList_ ] `{` { MethSig } `}` +
_InterfaceList_ ::= _TypeIdentifier_ { `,` _TypeIdentifier_ } +
_MethSig_ ::= _Type_ _Identifier_ `(` [ _Type_ _Identifier_ { `,` _Type_ _Identifier_ } ] `)` `;`
====

The interfaces in the example below represent a database system, providing
functionality to store and retrieve files, and a node of a peer-to-peer file
sharing system.  Each node of a peer-to-peer system plays both the role of a
server and a client.

[source]
.Example
----
interface DB {
  File getFile(Filename fId);
  Int getLength(Filename fId);
  Unit storeFile(Filename fId, File file);
  Filenames listFiles();
}
interface Client {
  List<Pair<Server,Filenames>> availFiles(List<Server> sList);

  Unit reqFile(Server sId, Filename fId);
}
interface Server {
  Filenames inquire();
  Int getLength(Filename fId);
  Packet getPack(Filename fId, Int pNbr);
}
interface Peer extends Client, Server {
  List<Server> getNeighbors();
}
----


== Classes

Classes in ABS are used to create objects via the `new` expression.  Classes
can implement an arbitrary number of interfaces.  Since classes are not types
in ABS, classes typically implement one or more interfaces.


Classes in ABS have zero or more _class parameters_.  Each class parameter
defines a field of the class which is assigned a value via arguments the `new`
expression.


Classes have an optional init block, which is executed before any other code.
The init block cannot contain processor release points (i.e., `await` or
`suspend`).



[caption=]
.Syntax
====
_ClassDecl_ ::= `class` _TypeIdentifier_ [ `(` [ _ClassParameterList_ ] `)` ] [ `implements` _InterfaceList_ ] +
`{` [ _FieldDeclList_ ] [ _Block_ ] [ _MethDeclList_ ] `}` +
_ClassParameterList_ ::= _Type_ _Identifier_ { `,` _Type_ _Identifier_ } +
_InterfaceList_ ::= _TypeIdentifier_ { `,` _TypeIdentifier_ } +
_FieldDeclList_ ::= { _Type_ _Identifier_ [ `=` _PureExp_ ] `;` } +
_MethDeclList_ ::= _Type_ _Identifier_ `(` [ _Type_ _Identifier_ { `,` _Type_ _Identifier_ } ] `)` _Block_
====





[source]
.Example
----
class DataBase(Map<Filename,File> db) implements DB {
	File getFile(Filename fId) {
		return lookup(db, fId);
	}

	Int getLength(Filename fId){
		return length(lookup(db, fId));
	}

	Unit storeFile(Filename fId, File file) {
		db = insert(Pair(fId,file), db);
	}

	Filenames listFiles() {
		return keys(db);
	}

	}

class Node(DB db, Peer admin, Filename file) implements Peer {

	Catalog catalog;
	List<Server> myNeighbors;
	// implementation...

}

----

.Active Classes

A class can be active or passive. Active classes start an activity on their own upon creation. Passive classes only react to incoming method calls. A class is active if and only if it has a run method:

[source]
----
Unit run() {
	// active behavior ...
}
----

The run method is called after object initialization.


== Deployment Components

A Deployment Component (abbreviated as `DC`) is 
the abstraction of a computational unit which is responsible for running ABS computations (programs).
Such a computational unit can either be realised by an OS process, physical machine, virtual machine
or a multitude of machines. By using DCs, the programmer can write ABS programs
that span across multiple computational units, similar to a distributed setting.

Based on the fact that a DC is a single *unit* that (pro)*actively* behaves (runs ABS code),
it is modelled as an _active object_, discussed in the previous section.
All DC objects are typed by the `DC` interface, defined in ABS as:

[source]
----
interface IDC {
  Unit shutdown();
  Triple<Rat,Rat,Rat> load();
}
----

With the `shutdown` method, a DC can safely be brought down, subsequently
freeing its occupied resources. The `load` method permits the user to probe for the
average load of the computational unit, that is how much utilized (busy) was the unit
in the last 1 , 5 and 15 minutes of execution. The following example is self-explanatory:

[source]

----
DC dc1 = new MyDC();
Fut<Triple<Rat,Rat,Rat>> f_avgs = dc1 ! load();
Triple<Rat,Rat,Rat> avgs = f_avgs.get();
dc1 ! shutdown();
----

NOTE: The ABS language specification does not define any built-in DC classes.
It is in the discretion of the ABS backends to provide with suitable DC classes (implementations).

After a new DC object is created, its associated computational unit is started and
sits waiting to execute ABS computations. To start ABS computations, the user
must create (active) objects inside the remote computational unit. This is
called `object spawning', illustrated by the example:

[source]

----
[DC: dc1] Interf1 o1 = new Class1(params..);
o1 ! method1( params ..);
this.method2( o1 );
----

The `DC` annotation on a `new` creates a new object in the given DC. The created object can only be placed in a new COG.
The returned object reference (`o1` in the example) is treated as normal (can be passed to arguments, called for its methods, etc.).

The function `thisDC()` is provided that can be put anywhere inside an ABS program to return
the computational unit where the calling code executes in.

[source]
----
{
  DC whereami = thisDC();
}
----


