= Control Statements

Similar to Java, a  statement is each of the individual instructions of a program, like the variable declarations and expressions seen in previous sections. They always end with a semicolon (;), and are executed in the same order in which they appear in a program. ABS provides flow control statements that serve to specify what has to be done by our program, when, and under which circumstances. Statements in ABS are not evaluated to a value. If one wants to assign a value to statements it would be the *Unit* value.

== Block

This statement is also known as a *compund statement* and consists of a group of statement grouped together defining a name scope for variables. 

.Syntax 

[source,java]
----
{
a = a + 1;
n = n % 10;
}
----

== Selection statement

.Syntax

[source, java]
----
if (5 < x) {
y = 6;
} 
else {
y = 7;
}
if (True)
x = 5;


----

== Iteration statement (Loop)

.Syntax

[source, java]
----
while (x < 5)
x = x + 1;

----

== Variable Declaration Statements

A variable declaration statement is used to declare variables. A variable has an optional initialization expression for defining the initial value of the variable. The initialization expression is mandatory for variables of data types. It can be left out only for variables of reference types, in which case the variable is initialized with null. 

.Syntax

[source, java]
----
Bool b = True;
----

== Assign Statement 

The *Assign Statement* assigns a value to a variable or a field.

.Syntax

[source, java]
----
this.f = True;
x = 5;
----


== Await Statement

*Await Statements* suspend the current task until the given guard is true [7]. The task will not be suspended if the guard is already initially true. While the task is suspended, other tasks within the same COG can be activated. Await statements are also called scheduling points, because they are the only source positions, where a task may become suspended and other tasks of the same COG can be activated.

.Syntax

[source, java]
----
Fut<Bool> f = x!m();
await f?;
await this.x == True;
await f? & this.y > 5;
----

== Suspend Statement

A Suspend Statement causes the current task to be suspended.

[source, java]
----
suspend;
----

== Skip Statement

The Skip Statement is a statement that does nothing. It is only used when analysing a program.

== Assert Statement

An Assert Statement is a statement for asserting certain conditions.

[source, java]
----
assert x != null;
----

== Return Statement

A *Return Statement* defines the return value of a method. A return statement can only appear as a last statement in a method body.

[source, java]
----
return x;
----

== Expression Statement

An Expression Statement is a statement that only consists of a single expression. Such statements are only executed for the effect of the expression.

[source, java]
----
new C(x);

----

