/*
 * generated by Xtext 2.18.0
 */
package org.abs_models.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AbsRuntimeModule extends AbstractAbsRuntimeModule {
}
