/*
 * generated by Xtext 2.18.0
 */
package org.abs_models.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AbsStandaloneSetup extends AbsStandaloneSetupGenerated {

	public static void doSetup() {
		new AbsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
