/*
 * generated by Xtext 2.17.0.M1
 */
package org.abs_models.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AbsStandaloneSetup extends AbsStandaloneSetupGenerated {

	def static void doSetup() {
		new AbsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
