== ABS Backends

This section describes the available and supported backends for ABS.
Different backends have different purposes (simulation, code execution,
visualization).  Their respective section describes their features and usage.

The following table gives an overview of the features that different backends
have.

Real-Time ABS:: Simulating a dense-time clock, and language constructs
expressing delays and task deadlines.  Used for simulating time usage of ABS
models.
Resource Models:: Specification of resource availability (processor power,
bandwidth) of _Deployment Components_ and simulation of resource usage
deployed thereon.  Builds on the semantics of Real-Time ABS.
Deployment:: Running ABS code on a number of physical or virtual machines,
with support for creating new cogs remotely.
FLI:: Foreign-Language Interface, the ability to call backend-specific native
code from ABS.


.Backend Capabilities
|===
| Backend | Maude | Erlang | Haskell | Java


| Real-Time ABS
| yes
| yes
| -
| yes

| User-defined Schedulers
| yes
| partial
| -
| -

| Resource Models
| yes
| yes
| -
| yes

| Deployment
| -
| -
| yes
| yes

| FLI
| -
| -
| yes
| planned

| Model API
| -
| yes
| -
| -

|===


=== Maude Backend

The Maude backend is a high-level, executable semantics in rewriting logic of
the ABS language.  Due to its relatively compact nature, it serves as a
test-bed for new language features.

Executing a model on the Maude backend results in a complete snapshot of the system state after execution has finished.

The main drawback of the Maude backend is its relatively poor performance, making it not very suitable to simulate large models.

Features:

* CPU and bandwidth resources
* Simulation of resource usage on deployment components
* Timed semantics
* Executable formal semantics of the ABS language


==== How to run the Maude backend

Running a model on Maude involves compiling the code, then starting Maude with
the resulting file as input.

Compiling all files in the current directory into Maude is done with the following command:

  $ absc --maude *.abs -o model.maude

The model is started with the following commands:

  $ maude
  Maude> in model.maude
  Maude> frew start .

This sequence of commands starts Maude, then loads the compiled model and
starts it.  The resulting output is a dump of the complete system state after
execution of the model finishes.

In case of problems, check the following:

- `absc` should be in the path; check the `PATH` environment variable.
- `absfrontend.jar` should be in the environment variable `CLASSPATH`.


[[sec:erlang-backend]]
=== Erlang Backend

The Erlang backend runs ABS models on the Erlang virtual machine by
translating them into Erlang and combining them with a small runtime library
implementing key ABS concepts (cogs, futures, objects, method invocations) in
Erlang.

Executing an ABS model in Erlang currently returns the value of the last
statement of the main block; output via `ABS.StdLib.println` is printed on the
console.  For additional introspective and interactive capabilities, the
Erlang backend supports a Model API (see below).


==== How to run the Erlang backend

Running a model in Erlang involves compiling the ABS code, then compiling and
running the resulting Erlang code.

Compiling all files in the current directory into Erlang and starting the
resulting model is done with the following commands:

  $ absc --erlang *.abs
  $ gen/erl/run

This sequence of commands starts Erlang, then compiles the generated Erlang
code and starts it.  Type `gen/erl/run -h` for a list of options accepted by
the model.

==== Recording and replaying traces

ABS task scheduling is non-deterministic; i.e., when two tasks are enabled,
the cog will select an arbitrary one (but see <<sec:schedulers>>).  The erlang
backend can record a trace of scheduling decisions and replay it to precisely
reproduce the previous run.

To record a trace to a file `trace.json`, start the model with a parameter
`--record trace.json` or `-t trace.json`.

To replay an existing trace recorded in `trace.json`, start the model with
`--replay trace.json` or `-r trace.json`.

A trace can also be obtained from a running model via the Model API.  Assuming
the model is started on port 8080 (via a parameter `-p 8080`), the trace is
accessible at the url http://localhost:8080/trace.  A trace visualizer can be
found here: https://github.com/larstvei/ABS-traces.

==== Generating code coverage information

The Erlang backend can optionally generate code coverage information in a
format inspired by gnu `gcov` (see
https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html).  The coverage
information contains line numbers and execution count, but not the source code
itself.  This is sufficient for some tools to visualize code coverage, e.g.,
`cov-mode` for Emacs (https://github.com/AdamNiederer/cov).

To generate code coverage information, compile an abs model with the
`--debuginfo` switch, then run it as normal, i.e.,

  $ absc --erlang --debuginfo *.abs
  $ gen/erl/run

For each `.abs` file, running the model will generate a `.abs.gcov` file in
the directory `gen/erl/absmodel` after the simulation finishes.

=== Java Backend

The Java backend runs ABS models on the JVM by translating them into Java and
combining them with a runtime library implementing key ABS concepts.

The Java backend currently implements Core ABS, but does not implement
Real-Time ABS or resource modeling.  The Java backend currently does not
implement the Model API or SQLite connections.

==== How to run the Java backend

Compiling all files in the current directory into Java and starting the
resulting model is done with the following commands:

  $ absc --java *.abs -o model.jar
  $ java -jar model.jar

The first command compiles the ABS model, the second command starts Java and
runs the code contained in `model.jar`.  In case more than one abs file
contains a main block, an arbitrary main block is executed.

The source code of the generated classes can be inspected below the `gen/`
directory.

=== Haskell Backend

The Haskell backend translates ABS models to Haskell source code, 
consequently compiled through a Haskell compiler and executed by the machine.
The backend, albeit  a work in progress, already supports most ABS constructs
and, above that, augments the language with extra features, such as `Type Inference`,
`Foreign Imports` and real `Deployment Components`.

.Type Inference

With the feature of `Type Inference` enabled, the user can _optionally_ leave out
the declaration of types of certain expressions; the backend will be responsible
to infer those types and type-check them in the ABS program. The type inference
is _safe_, in the sense that it will not infer any wrong types (soundness property).

To make use of this feature, the user puts an underscore `_` in place
of where a type would normally be, as in this ABS block of code:

[source, java]

----
{ _ x = 3;
  Int y = 4; // type inference is optional
  x = x+y;
  _ l = Cons(x, Cons(y, Nil));
  _ s = length(l) + 4; }
----

NOTE: At the moment, the type inference cannot infer
_interface types_ as in `_ o = new Class();`.
It can however infer all the other types, that is Builtin, Algebraic, and Exception data types.
There is a plan to support this in the future.

.Foreign Imports

The Haskell backend extends the ABS module system with the ability
to include Haskell-written code inside the ABS program itself.
This feature is provided by the `foreign_import` keyword,
which syntactically follows that of the normal `import` keyword. To illustrate this:

[source, java]

----
module Bar;
...
foreign_import Vertex from Data.Graph;
foreign_import vertices from Data.Graph;
----

the programmer has imported the `Vertex` algebraic datatype and
the `vertices` function from the `Data.Graph` Haskell library module into an ABS module
named `Bar`. Any imported Haskell term will be treated as its ABS
counterpart. In the example case, the programmer may re-export the foreign terms
or use them as normal ABS terms:

[source]
----
{
  Graph g = empty_graph();
  List<Vertex> vs = vertices(g);
} 
----

NOTE: At the moment, the ABS programmer can reuse (with `foreign_import`)  Haskell's _Algebraic Data types_
and _Pure functions_, but not monadic IO code (Haskell code with side-effects). This restriction
is planned to be lifted in a later release of the backend.

.Deployment Components

The Haskell backend implements the ABS feature of Deployment Components, faithfully as described in Chapter 8.
The backend follows the view that Deployment Components are _virtual machines_ running in the Cloud.
As such, each single DC corresponds to one Cloud virtual machine (VM).

Two DC classes (implementations) are provided to support the http://opennebula.org/[OpenNebula] and
http://azure.microsoft.com[Microsoft Azure] cloud computing platforms accordingly:

[source, java]

----
class NebulaDC(CPU cpu, Mem memory) implements DC {
  ...      
}
----

[source, java]

----
class AzureDC(CPU cpu, Mem memory) implements DC {
  ...
}
----

The `CPU` and `Mem` datatypes are passed as arguments when creating the DC to parameterize
its computing resources. These datatypes are simple defined as type synonyms to
Int, but you can expect more sophisticated resource encodings for a future backend release.

[source]
----
type CPU = Int; // processor cores
type Mem = Int; // RAM measured in MB
----

[WARNING]
The backend has only been developed on and tested against the OpenNebula platform.
This hopefully will change when more cloud providers will be supported.

==== How to obtain and install

The compiler itself is written in Haskell and distributed as a normal Haskell package. Therefore to build abs2haskell you need either

1) a recent release of the https://www.haskell.org/platform/[Haskell platform] (version >= 2013.2.0.0),

2) the GHC compiler accompanied by the Cabal packaging system:

    - GHC compiler (version >=7.6)
    - Cabal package (version >=1.4)
    - `cabal-install` program. The compiler depends on other community
packages/libraries. This program will automatically fetch
and install any library dependencies.

.Downloading, building and installing the compiler

Clone the repository with the command:

      $ git clone git://github.com/bezirg/abs2haskell

To build and install the abs2haskell backend run inside the `abs2haskell/` directory:

[source]

----
sudo make install
----

==== How to run the Haskell backend

After installing the compiler, you should
have the program `abs2haskell` under your `PATH`.

Examples of running:

[source]

----
$ abs2haskell Example.abs 

# An ABS program may have multiple main blocks in different modules. 
# So you have to specify in which module is the main block you want to build with

$ abs2haskell --main-is=Example.abs Example.abs 

$ abs2haskell examples/   # will compile all ABS files under examples directory
----


The compiler will generate ".hs" files for each compiled ABS module.
No other runtime system libraries and dependencies will be generated.


The final step before running the ABS program is to compile the generated Haskell code to machine code, as the example:

[source]

----
ghc --make -threaded Example.hs # put the generated haskell file that has the main block here
----

.Running the final program

[source]

----
./Example -O # means run it on 1 core with default optimizations
./Example -O +RTS -N1 # the same as the above
./Example -O +RTS -N2 # run it on 2 cores
./Example -O +RTS -N4 # run it on 4 cores
./Example -O +RTS -NK # run it on K cores
----
