== Deployment Components

A Deployment Component (abbreviated as `DC`) is 
the abstraction of a computational unit which is responsible for running ABS computations (programs).
Such a computational unit can either be realised by an OS process, physical machine, virtual machine
or a multitude of machines. By using DCs, the programmer can write ABS programs
that span across multiple computational units, similar to a distributed setting.

Based on the fact that a DC is a single *unit* that (pro)*actively* behaves (runs ABS code),
it is modelled as an _active object_, discussed in the previous section.
All DC objects are typed by the `DC` interface, defined in ABS as:

[source]
----
interface IDC {
  Unit shutdown();
  Triple<Rat,Rat,Rat> load();
}
----

With the `shutdown` method, a DC can safely be brought down, subsequently
freeing its occupied resources. The `load` method permits the user to probe for the
average load of the computational unit, that is how much utilized (busy) was the unit
in the last 1 , 5 and 15 minutes of execution. The following example is self-explanatory:

[source, java]

----
DC dc1 = new MyDC();
Fut<Triple<Rat,Rat,Rat>> f_avgs = dc1 ! load();
Triple<Rat,Rat,Rat> avgs = f_avgs.get();
dc1 ! shutdown();
----

[NOTE]
The ABS language specification does not define any built-in DC classes.
It is in the discretion of the ABS backends to provide with suitable DC classes (implementations).

After a new DC object is created, its associated computational unit is started and
sits waiting to execute ABS computations. To start ABS computations, the user
must create (active) objects inside the remote computational unit. This is
called `object spawning', illustrated by the example:

[source, java]

----
[DC: dc1] Interf1 o1 = new Class1(params..);
o1 ! method1( params ..);
this.method2( o1 );
----

The `DC` annotation on a `new` creates a new object in the given DC. The created object can only be placed in a new COG.
The returned object reference (`o1` in the example) is treated as normal (can be passed to arguments, called for its methods, etc.).

The function `thisDC()` is provided that can be put anywhere inside an ABS program to return
the computational unit where the calling code executes in.

[source]
----
{
  DC whereami = thisDC();
}
----

