package abs.frontend.parser;

/**
 * @author rudi
 * Interface to the errors generated by the parser.
 */
public interface ParserError {
	/**
	 * @return the associated error message.
	 */
	public String getMessage();
	/**
	 * @return the line number of the error, or -1 if unavailable.
	 */
	public int getLine();
	/**
	 * @return the column number of the error, or -1 if unavailable.
	 */
	public int getColumn();
}
