== Deltas

ABS supports the delta-oriented programming model, an approach that aids the
development of a set of programs simultaneously from a single code base,
following the software product line engineering approach.  In delta-oriented
programming, features defined by a feature model are associated with code
modules that describe modifications to a core program.  In ABS, these modules
are called _delta modules_. Hence the implementation of a software product
line in ABS is divided into a _core_ and a set of delta modules.

The core consists of a set of ABS modules that implement a complete software
product of the corresponding software product line.  Delta modules (or
_deltas_ in short) describe how to change the core program to obtain new
products.  This includes adding new classes and interfaces, modifying existing
ones, or even removing some classes from the core.  Delta modules can also
modify the functional entities of an ABS program, that is, they can add and
modify data types and type synonyms, and add functions.

Deltas are applied to the core program by the ABS compiler front end. The
choice of which delta modules to apply depends on the selection of a set of
features, that is, a particular product of the SPL.  The role of the ABS
compiler front end is to translate textual ABS models into an internal
representation and check the models for syntax and semantic errors.  The role
of the back ends is to generate code for the models targeting some suitable
execution or simulation environment.

[source]
----
DeltaDecl      ::= 'delta' TypeId [DeltaParams] ';' [ModuleAccess] ModuleModifier*
ModuleModifier ::= 'adds' ClassDecl
                 | 'removes' 'class' TypeName ';'
                 | 'modifies' 'class' TypeName
                   ['adds' TypeId (',' TypeId)*] ['removes' TypeId (',' TypeId)*]
                   '{' Modifier* '}'
                 | 'adds' InterfaceDecl
                 | 'removes' 'interface' TypeName ';'
                 | 'modifies' 'interface' TypeName '{' InterfaceModifier* '}'
                 | 'adds' FunctionDecl
                 | 'adds' DataTypeDecl
                 | 'modifies' DataTypeDecl
                 | 'adds' TypeSynDecl
                 | 'modifies' TypeSynDecl
                 | 'adds' Import
                 | 'adds' Export

InterfaceModifier ::= 'adds' MethSig ';'
                    | 'removes' MethSig ';'

Modifier ::= 'adds' FieldDecl
           | 'removes' FieldDecl
           | 'adds' MethDecl
           | 'removes' MethSig
           | 'modifies' MethDecl
        
DeltaParams ::= '(' DeltaParam (',' DeltaParam)* ')'

DeltaParam ::= Identifier HasCondition*
             | Type Identifier

ModuleAccess ::= 'uses' TypeId ';'

HasCondition ::= 'hasField' FieldDecl
               | 'hasMethod' MethSig
               | 'hasInterface' TypeId
----

The `DeltaDecl` clause specifies the syntax of delta modules, consisting of a
unique identifier, a module access directive, a list of parameters and a
sequence of module modifiers.  The _module access_ directive gives the delta
access to the namespace of a particular module.  In other words, it specifies
the ABS module to which modifications using unqualified identifiers apply by
default.  A delta can still make changes to several modules by fully
qualifying the `TypeName` of module modifiers.

While delta modelling supports a broad range of ways to modify an ABS model,
not all ABS program entities are modifiable.  These unsupported modifications
are listed here for completeness.  While these modifications could be easily
specified and implemented, we opted not to overload the language with features
that have not been regarded as necessary in practice:

Class parameters and init block::
Deltas currently do not support the modification of class parameter lists or
class init blocks.
Deltas::
currently only support adding functions, and adding and modifying data types
and type synonyms. Removal is not supported.
Modules::
Deltas currently do not support adding new modules or removing modules.
Imports and Exports::
While deltas do support the addition of import and export statements to
modules, they do not support their modification or removal.
Main block::
Deltas currently do not support the modification of the program’s main block.

