#!/bin/bash
# Arild Torjusen April 2010

BASEDIR="@BASEDIR@" 

files="PeerToPeer.abs block.abs boundedbuffer.abs emptyblock.abs expressions.abs failblock.abs pingpong.abs skeleton.abs skipblock.abs statements.abs trivial.abs"

function usage
{
    echo 'Usage: parseAll [-v]'
    echo 'Parses all ABS samples'
}


while getopts ":v" Option
do
  case $Option in
    v ) verbose="-v";;
    * ) echo "Illegal option: $1";usage;exit 1;;      
  esac
done
shift $(($OPTIND - 1))

for f in $files ; do 
args="$args tests/abssamples/$f" 
done 
echo "parsing files in ./tests/abssamples/ : "; 
echo $files; 
eval bin/parseABS $verbose $args 


exit 0


