#!/bin/bash
# A simple script to create ABS packages
#
# Copyright (c) 2009-2011, The HATS Consortium. All rights reserved. 
# This file is licensed under the terms of the Modified BSD License.
#
# Author: Jan Schäfer
# 
# Versions: 1.0 - initial version
#

die() {
  echo >&2 "$@" 
  echo >&2 "Usage: $0 jar-file <absfiles>"
  exit 1
}

[[ $# -ge 1 ]] || die "Please provide the name of the ABS package to be created"

MANIFEST=`mktemp`
echo 'ABS-Package-Version: 1.0' >> $MANIFEST
jar cfm "$1" $MANIFEST $@

rm $MANIFEST
