== The Model API

The Erlang backend supports querying a running model.  When creating objects,
an annotation `HTTPName` makes them available via HTTP requests from outside
the model under the name given by the annotation.  Methods that are annotated
`HTTPCallable` can be invoked from the outside on such objects.  Additionally,
datatypes can be annotated to influence how they are converted to JSON when
they are returned from such methods.

The model API is supported by the Erlang backend.

=== Starting the Model API

When an ABS model compiled with the Erlang backend is started with the `-p`
parameter naming a port number, the model will listen on the specified port
for requests.  In the following example, we compile a model `my-model.abs` and
start the model API on port 8080:

----
$ absc -erlang my-model.abs
$ gen/erl/run -p 8080
----

=== Shutting down the Model API

When running a model with the model API activated, it will not return to the
command line after the simulation has finished.  Instead, the model will keep
listening for requests and method calls.

A running model can be terminated manually from the console (for example, via
pressing `Ctrl-C`), or by requesting the URL `/quit`.  The following command
will terminate a model running on port 8080:

----
$ curl localhost:8080/quit
curl: (52) Empty reply from server
----


=== Exposing objects

Objects are exposed via a `HTTPName` annotation.  In the following example,
two objects of class `C` are exposed with the names `C1` and `C2`
respectively.  The `HTTPName` annotation can be used on assignment statements,
variable declarations and `new` expression statements.

----
[HTTPName: "C1"] new C();
[HTTPName: "C2"] I x = new C();
----

=== Exposing methods

In an interface declaration, a `HTTPCallable` annotation exposes the annotated
method such that it is callable from outside, given an exposed object that implements that interface.

----
interface I {
  [HTTPCallable] String method(String param1, Int param2);
}
----

It is a compile-time error if the method takes parameters whose types are not
supported.

Currently supported parameter types are:

- `Bool`: encoded in the query string as literal upper- or lowercase `true` /
  `false`: `?p=True`, `?p=true`, `?p=False`, `?p=false`

- `Int`: encoded in the query string as a string of digits, e.g., `?p=42`

- `String`: URLEncoded text, e.g., `?p=Hello%20World!`

The method can have an arbitrary return type, which will be returned as a
string via the ABS `toString()` function, except for the following cases.

The following value types are handled specially as return type of an exposed
method:

- `Bool`, encoded as a JSON boolean value

- `String`, encoded as a JSON string value

- `Int`, encoded as a JSON integer.

- `Rat`, converted to a floating point number.  The behavior is unspecified if
  the given value is outside of floating point range.

- `List<A>` (for supported type `A`), encoded as a JSON list

- `Set<A>` (for supported type `A`), encoded as a JSON list; guaranteed to
  contain no duplicate elements

- `Map<A, B>` (for supported types `A`, `B`), encoded as a JSON object.  Keys
  in the resulting JSON object are generated from their ABS counterpart via
  `toString()` since JSON only supports keys of type String.

- Datatypes with at least one named constructor argument, or a constructor
  argument with `HTTPName` annotation: encoded as a JSON object mapping
  argument names to their value.  The resulting map will not contain the
  values of unnamed / unannotated constructor arguments.  When an argument is
  both named and annotated, the annotation takes precedence.

In the following example, a return value `D1("x", 1)` will be encoded as
`{"key": "x"}`, while `D2("x", 1)` will be encoded as `{"effective key":
"x"}`.  Note that the second parameter is skipped since it has neither an
accessor function nor an `HTTPName` annotation.

----
data D1 = D(String key, Int);
data D2 = D([HTTPName: "effective key"] String overridden, Int);
----

=== Querying object state

The following query returns the names of all exposed objects.

----
GET http://localhost:8080/o
----

Inspecting an object state directly can be useful for debugging.  The
following query returns a JSON map of the state of the object exposed as `C1`,
with object fields as keys.

----
GET http://localhost:8080/o/C1
----

The following query returns a JSON map containing the value of `C1`'s `field`,
with `"field"` as key.

----
GET http://localhost:8080/o/C1/field
----

When querying for an unknown object or an unknown field, the HTTP request will
produce a 404 response code.

NOTE: All queries in this section can be prepended with a `/v2/` prefix, i.e.,
`http://localhost:8080/v2/o`.  In case incompatible changes are introduced
to the Model API in the future, for example by introducing new return value
encodings, reasonable effort will be made to keep the semantics of invocations
of queries with prefix `/v2/` unchanged.



=== Invoking methods

The following query returns, for an object exposed as `C1`, a JSON array of
objects with metadata about callable functions.

----
GET http://localhost:8080/call/C1
----

The map has the following entries:

- `name`: the name of the exposed method
- `parameters`: an array with one object per parameter, each with the
  following entries:
  - `name`: name of the parameter
  - `type`: type of the parameter
- `return`: return type of the method

The following query produces the return value of the method call
`method("value", 50)` by invoking it on the object exposed as `C1`.

----
GET http://localhost:8080/call/C1/method?param1=value&param2=50
----

Care must be taken to disable timeouts on the HTTP client when querying for
long-running methods in this way.

When querying for unknown objects or methods, the HTTP request will produce a
404 response code.

When querying with invalid method parameters, the HTTP request will produce a
400 response code.

When the invoked method throws an exception, the HTTP request will produce a
500 response code.

NOTE: All queries in this section can be prepended with a `/v2/` prefix, i.e.,
`http://localhost:8080/v2/call`.  In case incompatible changes are
introduced to the Model API in the future, for example by introducing new
return value encodings, reasonable effort will be made to keep the semantics
of invocations of queries with prefix `/v2/` unchanged.
