== Erlang Backend

The Erlang backend runs ABS models on the Erlang virtual machine by
translating them into Erlang and combining them with a small runtime library
implementing key ABS concepts (cogs, futures, objects, method invocations) in
Erlang.

Executing an ABS model in Erlang currently returns the value of the last
statement of the main block; output via `ABS.Meta.println` is printed on the
console.  More introspective and interactive capabilities are planned and will
be implemented in the future.


=== How to run the Erlang backend

Running a model in Erlang involves compiling the ABS code, then compiling and
running the resulting Erlang code.

Compiling all files in the current directory into Erlang is done with the following command:

  $ absc -erlang *.abs

The model is started with the following commands, where `/Modulename/` should
be the name of the module containing the main block:

  $ erl
  1> code:add_path("gen/erl/ebin").
  2> cd ("gen/erl").
  3> make:all([load]).
  4> runtime:start("/Modulename/").

This sequence of commands starts Erlang, then compiles the generated Erlang
code and starts it.


