== Haskell Backend

The Haskell backend translates ABS models to Haskell source code, 
consequently compiled through a Haskell compiler and executed by the machine.
The backend, albeit  a work in progress, already supports most ABS constructs
and, above that, augments the language with extra features, such as `Type Inference`,
`Foreign Imports` and real `Deployment Components`.

.Type Inference

With the feature of `Type Inference` enabled, the user can _optionally_ leave out
the declaration of types of certain expressions; the backend will be responsible
to infer those types and typecheck them in the ABS program. The type inference
is _safe_, in the sense that it will not infer any wrong types (soundness property).

To make use of this feature, the user puts an underscore `_` in place
of where a type would normally be, as in this ABS block of code:

[source, java]

----
{ _ x = 3;
  Int y = 4; // type inference is optional
  x = x+y;
  _ l = Cons(x, Cons(y, Nil));
  _ s = length(l) + 4; }
----

[NOTE]
At the moment, the type inference cannot infer
_interface types_ as in `_ o = new Class();`.
It can however infer all the other types, that is Builtin, Algebraic, and Exception data types.
There is a plan to support this in the future.

.Foreign Imports

The Haskell backend extends the ABS module system with the ability
to include Haskell-written code inside the ABS program itself.
This feature is provided by the `foreign_import` keyword,
which syntactically follows that of the normal `import` keyword. To illustrate this:

[source, java]

----
module Bar;
...
foreign_import Vertex from Data.Graph;
foreign_import vertices from Data.Graph;
----

the programmer has imported the `Vertex` algebraic datatype and
the `vertices` function from the `Data.Graph` Haskell library module into an ABS module
named `Bar`. Any imported Haskell term will be treated as its ABS
counterpart. In the example case, the programmer may re-export the foreign terms
or use them as normal ABS terms:

[source]
----
{
  Graph g = empty_graph();
  List<Vertex> vs = vertices(g);
} 
----

[NOTE]

At the moment, the ABS programmer can reuse (with `foreign_import`)  Haskell's _Algebraic Data types_
and _Pure functions_, but not monadic IO code (Haskell code with side-effects). This restriction
is planned to be lifted in a later release of the backend.

.Deployment Components

The Haskell backend implements the ABS feature of Deployment Components, faithfully as described in Chapter 8.
The backend follows the view that Deployment Components are _virtual machines_ running in the Cloud.
As such, each single DC corresponds to one Cloud virtual machine (VM).

Two DC classes (implementations) are provided to support the http://opennebula.org/[OpenNebula] and
http://azure.microsoft.com[Microsoft Azure] cloud computing platforms accordingly:

[source, java]

----
class NebulaDC(CPU cpu, Mem memory) implements DC {
  ...      
}
----

[source, java]

----
class AzureDC(CPU cpu, Mem memory) implements DC {
  ...
}
----

The `CPU` and `Mem` datatypes are passed as arguments when creating the DC to parameterize
its computing resources. These datatypes are simple defined as type synonyms to
Int, but you can expect more sophisticated resource encodings for a future backend release.

[source]
----
type CPU = Int; // processor cores
type Mem = Int; // RAM measured in MB
----

[WARNING]
The backend has only been developed on and tested against the OpenNebula platform.
This hopefully will change when more cloud providers will be supported.

=== How to obtain and install

The compiler itself is written in Haskell and distributed as a normal Haskell package. Therefore to build abs2haskell you need either

1) a recent release of the https://www.haskell.org/platform/[Haskell platform] (version >= 2013.2.0.0),

2) the GHC compiler accompanied by the Cabal packaging system:

    - GHC compiler (version >=7.6)
    - Cabal package (version >=1.4)
    - `cabal-install` program. The compiler depends on other community
packages/libraries. This program will automatically fetch
and install any library dependencies.

.Downloading, building and installing the compiler

Clone the repository with the command:

      $ git clone git://github.com/bezirg/abs2haskell

To build and install the abs2haskell bakend run inside the `abs2haskell/` directory:

[source]

----
sudo make install
----

=== How to run the Haskell backend

After installing the compiler, you should
have the program `abs2haskell` under your `PATH`.

Examples of running:

[source]

----
$ abs2haskell Example.abs 

# An ABS program may have multiple main blocks in different modules. 
# So you have to specify in which module is the main block you want to build with

$ abs2haskell --main-is=Example.abs Example.abs 

$ abs2haskell examples/   # will compile all ABS files under examples directory
----


The compiler will generate ".hs" files for each compiled ABS module.
No other runtime system libraries and dependencies will be generated.


The final step before running the ABS program is to compile the generated Haskell code to machine code, as the example:

[source]

----
ghc --make -threaded Example.hs # put the generated haskell file that has the main block here
----

.Running the final program

[source]

----
./Example -O # means run it on 1 core with default optimizations
./Example -O +RTS -N1 # the same as the above
./Example -O +RTS -N2 # run it on 2 cores
./Example -O +RTS -N4 # run it on 4 cores
./Example -O +RTS -NK # run it on K cores
----

