= ABS Backends

This section describes the available and supported backends for ABS.
Different backends have different purposes (simulation, code execution,
visualization).  Their respective section describes their features and usage.

The following table gives an overview of the features that different backends
have.

Real-Time ABS:: Simulating a dense-time clock, and language constructs
expressing delays and task deadlines.  Used for simulating time usage of ABS
models.
Resource Models:: Specification of resource availability (processor power,
bandwidth) of _Deployment Components_ and simulation of resource usage
deployed thereon.  Builds on the semantics of Real-Time ABS.
Deployment:: Running ABS code on a number of physical or virtual machines,
with support for creating new cogs remotely.
FLI:: Foreign-Language Interface, the ability to call backend-specific native
code from ABS.


.Backend Capabilities
|===
| Backend | Maude | Erlang | Haskell | Java


| Real-Time ABS
| yes
| partly implemented (no deadlines)
| -
| -

| Resource Models
| yes
| yes
| -
| -

| Deployment
| -
| -
| yes
| ?

| FLI
| -
| -
| yes
| planned

|===


include::maude.adoc[]
include::erlang.adoc[]
include::haskell.adoc[]
include::keyabs.adoc[]


