== KeY-ABS Backend

http://www.key-project.org/key-abs/README-KeY-ABS_0.1.0-src.txt[KeY-ABS]
is a proof checker for ABS models.  It can be downloaded from
http://www.key-project.org/key-abs/key-abs.zip.

The KeY-ABS backend can be used to generate invariants from
annotations in the ABS source code.  A design goal is to support
annotations written in familiar ABS syntax; some invariants that can
be expressed in KeY syntax proper might not be expressible in the
ABS-flavored annotation syntax.

This backend is a work-in-progress and under active development.

Features:

* Class invariants over Integer-typed fields

Limitations / Future Work:

* Support of other datatypes in invariants
* Support of ABS functions in invariants
* Support of pre- and postconditions of methods, in interfaces and
  classes

=== Expressing a class invariant

A class Invariant is a Boolean condition over the object's fields.  It is written using an `Inv` annotation in the following way:

.Example
--------------------------------------------------
module Account;
export *;

interface Account { 
	Int getAid();
	Int deposit(Int x); 
	Int withdraw(Int x);
	Int withdrawAsync(Int x);

	Bool transfer(Int amount, Account target);

}

[Inv: balance >= 0 && aid >= 0] <1>
class AccountImpl(Int aid, Int balance) implements Account {

    Int getAid() { return aid; }
    [Pre: x >= 0]
    Int deposit(Int x) { balance = balance + x; return balance;}
    Int withdraw(Int x) { 
	if (balance - x >= 0) {
	    balance = balance - x;
	} 
	return balance;
    }


    Int withdrawAsync(Int x) { 
	Fut<Int> resFut = this!withdraw(x);
	await resFut?;
	return balance;
    }
	


    Bool transfer(Int amount, Account target) {
	Bool success = False;
	if (balance - amount >= 0) {
	    Fut<Int> newBal = this!withdraw(amount);
	    await newBal?;
	    Fut<Int> result = target!deposit(amount);
	    await result?;
	    success = True;
	}
	return success;
    }
}

{
	new AccountImpl(1,1);
}
--------------------------------------------------
<1> The `Inv` annotation defines a class invariant expressing that
`balance` and `aid` must be non-negative integers


=== How to run the KeY-ABS backend

Proving the correctness of a model involves generating the invariants,
then running KeY-ABS with the resulting file as input.

Generating invariants for all files in the current directory is done
with the following command:

  $ absc -keyabs *.abs -o model.inv

This generated file can then be used with KeY-ABS in the usual way.

