== Maude Backend

The Maude backend is a high-level, executable semantics in rewriting logic of
the ABS language.  Due to its relatively compact nature, it serves as a
test-bed for new language features.

Executing a model on the Maude backend results in a complete snapshot of the system state after execution has finished.

The main drawback of the Maude backend is its relatively poor performance, making it not very suitable to simulate large models.

Features:

* CPU and bandwidth resources
* Simulation of resource usage on deployment components
* Timed semantics
* Executable formal semantics of the ABS language


=== How to run the Maude backend

Running a model on Maude involves compiling the code, then starting Maude with
the resulting file as input, with the file `abs-interpreter.maude` accessible
to Maude.

Compiling all files in the current directory into Maude is done with the following command:

  $ absc -maude *.abs -o model.maude

The model is started with the following commands:

  $ maude
  Maude> in model.maude
  Maude> frew start .

This sequence of commands starts Maude, then loads the compiled model and
starts it.  The resulting output is a dump of the complete system state after
execution of the model finishes.

In case of problems, check the following:

- `absc` should be in the path; check the `PATH` environment variable.
- `absfrontend.jar` should be in the environment variable `CLASSPATH`.
- `abs-interpreter.maude` should be in the same directory as the compiled
  model, or in a directory listed in the environment variable `MAUDE_LIB`.


