=== Algebraic Data Types

Algebraic Data Types make it possible to describe data in an immutable way. In contrast to objects, data types do not have an identity and cannot be mutated. This makes reasoning about data types much simpler than about objects. Data types are built by using Data Type Constructors (or constructors for short), which describe the possible values of a data type.

.Syntax
[source]
----
data IntList = NoInt | Cons(Int, IntList);
data Bool = True | False;
----

.Parametric Data Types
Parametric Data Types are useful to define general-purpose data types, such as lists, sets or maps. Parametric data types are declared like normal data types but have an additional type parameter section inside broken brackets (< >) after the data type name.

----
data List<A> = Nil | Cons(A, List<A>);
----

.Predefined Algebraic Data Types

The following Algebraic Data Types are predefined and come bundled with the ABS standard library:

* data Bool = True | False;++ The boolean type with constructors True and False and the usual Boolean infix and prefix operators. 
* data Unit = Unit;++ The unit type with only one constructor Unit (for methods without return values).
* data Int; An arbitrary integer (Z) for which values are constructed by using integer literals and arithmetic expressions.
* data Rat;. A rational number (Q). Rational values are obtained via the division (/) operator and have arbitrary precision. Assigning rational values to variables of type Int, either explicitly or implicitly by passing them to a function or method expecting an integer, rounds towards zero.
* data String;. A string for which values are constructed by using string literals and operators.
* data Fut<T>;. Representing a future. A future cannot be explicitly constructed, but it is the result of an asynchronous method call. The value of a future can only be obtained by using the get expression.
* data List<A> = Nil | Cons(A, List<A>)++ Where Nil is the empty list, and Cons appends an element of type A in the front of the list.

.N-ary Constructors
For data types of arbitrary size, like lists, maps and sets, it is undesirable having to write them down in the form of nested constructor expressions. For this purpose, ABS provides a special syntax for nary constructors, which are transformed into constructor expressions via a user-supplied function.·

.Syntax
[source]
----
def Set<A> set<A>(List<A> l) = case l {
    Nil => EmptySet;
    Cons(hd, tl) => Insert(hd, set(tl));
    };

{
Set<Int> s = set[1, 2, 3];
}
----

An expression type[parameters*] is transformed into a literal by handing it to a function named type which takes one parameter of type List and returns an expression of type Type. (It is desirable, although not currently enforced, that type and Type are the same word, just with different capitalization.)


.Abstract Data Types
Using the module system it is possible to define abstract data types. For an abstract data type, only the functions that operate on them are known to the client, but not its constructors.
This can be easily realized in ABS by putting such a data type in its own module and by only exporting the data type and its functions, without exporting the constructors.

