=== Built-in Types

The most basic of built-in types is the +Int+ type, which represents integers of arbitrary size.
Values of type +Int+ can be constructed by using integer
literals or arithmetic expressions: 

----
0  has type Int
1  has type Int
3  has type Int
3+1  has type Int
----

A related type is the +Rat+ for representing rational numbers.
Rational values are obtained via the division (/) operator and have arbitrary precision.
An example of such values:

----
1/4   has type Rat
5/2/4 has type Rat
----

The +Int+ type is a subtype of +Rat+; this means that
+Int+ expressions are automatically converted to +Rat+ expressions,
whenever a +Rat+ type is expected. Some examples of +Rat+ expressions:

----
0 can also have type Rat
1 can also have type Rat
4+3 can also have the Rat
----

[NOTE]
The adverse does not work. The user that wants to convert from
+Rat+ to +Int+ types have to explicitly use the +truncate(number)+ function.


The +String+ built-in type represents String values, constructed either by string literals
or by string-specific operators coming from the ABS standard library. Examples
of Strings:

----
"hello world\n"  is a string literal
"standard" + "library" is a string expression (concatenation)
----

[NOTE]
According to other functional languages, Strings in ABS are immutable data.
Desimilar to other function languages, ABS Strings are not represented as list of
characters; instead they have a hidden-to-the-user, efficient, internal representation.


The +Fut+ type is a special built-in type to signal an ABS value that will become
available (evaluated) in the future. +Fut+ is a so-called parameterized type, 
written as +Fut<T>+, where T is its type parameter. The value that a future
holds and will return can be of any concrete type, as in the example: 

----
Fut<String> is the type that will return a string
Fut<List<Rat>> is the type that will return a list of rational numbers
----

The +Unit+ , +Bool+ and +List+ types, albeit not built-in, are bundled together with the other built-in types inside the ABS language.
They are defined using the "Algebraic Data Type syntax" (ADT), detailed in the next link:algebraic.html[section]:

[source, java]

----
data Unit = Unit;
data Bool = True | False;
data List<A> = Nil | Cons(A, List<A>);
----
