=== The Exception Type

In higher-level programming languages, exceptions are generally used to signal an _erroneous_ or _abnormal_
runtime behaviour of the program, that should be treated (handled) separately compared to normal values.

The Exception type is a special built-in data type that looks similar to an Algebraic Data Type (immutable, no identity) 
but with a notable difference: the exception data type *can* be extended
with new (user-provided) data constructors. Based on this fact,
the user has the ability to, besides using the predefined exceptions of the ABS standard library,
write arbitrary exceptions specific to the user's program.

To define a new exception (data constructor) the user has to write:

[source, java]

----
exception MyException;
----

An exception can also take any number of arguments as:

[source, java]

----
exception AnotherException(Int, String, Bool);
----

In ABS, exceptions are first-class citizens of the language;
the user can construct exception-values, assign them to variables or pass them in expressions.
All these exception-values are typed by the type +Exception+ . 
However, an exception-value can only acquire the special meaning of abnormal behaviour
when the user explicitly says so with a +throw+ keyword. We will visit the +throw+ keyword
together with how to recover from exceptions (+catch+ keyword) in a later section.

.Predefined exceptions in the Standard Library

DivisionByZeroException::
    Raised in arithmetic expressions when the divisor (denominator) is equal to 0, as in +3/0+
AssertionFaiException::
    The assert keyword was called with +False+ as argument
PatternMatchFailException::
    The pattern matching was not complete. In other words all c catch-all clause
NullPointerException::
    A method was called on a null object
StackOverflowException::
    The calling stack has reached its limit (system error)
HeapOverflowException::
    The memory heap is full (system error)
KeyboardInterruptException::
    The user pressed a key sequence to interrupt the running ABS program

