== Lexical Structure

This section describes the lexical structure of the ABS language. ABS programs are written in Unicode.

.Line Terminators and White Spaces

Line terminators and white spaces are defined as in Java.

.Comments
Comments are code fragments that are completely ignored and have no semantics in the ABS language. ABS supports two styles of comments: end-of-line comments and traditional comments.

.End-Of-Line Comments

An end-of-line comment is a code fragment that starts with two slashes, e.g., `//` text. All text that follows `//` until the end of the line is treated as a comment.

.Syntax

[source]
----
// this is a comment
module A; // this is also a comment
----

.Traditional Comments
A traditional comment is a code fragment that is enclosed in `/{asterisk} {asterisk}/`, e.g., `/{asterisk} this is a comment {asterisk}/`. Nested traditional comments are not possible.

[source]
----
/* this
is a multiline
comment */

----

.Identifiers

Identifiers consist of a letter followed by a sequence of letters,
numbers and underscores (`_`).

ABS distinguishes identifiers and type identifiers.  Identifiers start
with a lower-case character, type identifiers start with an upper-case
character.  Identifiers name local variables, fields and functions.
Type identifiers name interfaces, classes, types and type
constructors.

.Keywords
The following words are keywords in the ABS language and are not regarded as identifiers.

[options= "header, footer",format="csv", "ls="7",grid="none"]
|=====

adds,core,export,hasMethod,let,product,this
after,class,features,if,local,productline,type
assert,data,from,implements,modifies,removes,when
await,def,get,import,module,return,while
builtin,delta,hasField,in,new,skip,case
else,hasInterface,interface,null,suspend

|=====

.Literals
A literal is a textual representation of a value. ABS supports three kinds of literals, integer literals, string literals, and the null literal.

.Separators
The following characters are separators:

[format="csv",width="60%",cols="9"]
[frame="topbot",grid="none"]
|=====
(,),{,},[,],\,,\;,:
|=====

.Operators


The following tokens are operators:

[format="csv",width="60%",cols="15"]
[frame="topbot",grid="none"]
|=====
||,&&,==,!=,<,>,<=,>=,+,-,*,/,%,!,&
|=====

.Annotations

Annotations consist of a type identifier, optionally followed by a
colon (`:`) and a syntactically valid pure expression.  They can be
put in front of statements and definitions.

Unknown annotations are ignored by the toolchain.

[source]
----
[Near] class Example { ... }
----

This is an example of an annotation with an expression:

[source]
----
[Cost: 15] skip;
----

