== Lexical Structure

This section describes the lexical structure of the ABS language. ABS programs are written in Unicode.

.Line Terminators and White Spaces

Line terminators and white spaces are defined as in Java.

.Comments
Comments are code fragments that are completely ignored and have no semantics in the ABS language. ABS supports two styles of comments: end-of-line comments and traditional comments.

.End-Of-Line Comments

An end-of-line comment is a code fragment that starts with two slashes, e.g., `//` text. All text that follows `//` until the end of the line is treated as a comment.

.Syntax

[source,java]

----
// this is a comment
module A; // this is also a comment
----

.Traditional Comments
A traditional comment is a code fragment that is enclosed in `/{asterisk} {asterisk}/`, e.g., `/{asterisk} this is a comment {asterisk}/`. Nested traditional comments are not possible.

[source,java]

----
/* this
is a multiline
comment */

----

.Identifiers
ABS distinguishes identifier and type identifier. They differ in the first character, which must be a lower-case character for identifiers and an upper-case character for type identifiers.

.Keywords
The following words are keywords in the ABS language and are not regarded as identifiers.

[format="csv",width="60%",cols="7"]
[frame="topbot",grid="none"]
|=====
adds,cog,else,hasInterface,interface,product,this
after, core,export,hasMethod,let,productline,type
assert,class,features,if,modifies,removes,when
await,data,from,implements,module,return,while
builtin,def,get,import,new,skip
case,delta,hasField,in,null,suspend
|=====

.Literals
A literal is a textual representation of a value. ABS supports three kinds of literals, integer literals, string literals, and the null literal.

.Separators
The following characters are separators:

[format="csv",width="60%",cols="9"]
[frame="topbot",grid="none"]
|=====
(,),{,},[,],\,,\;,:
|=====

.Operators


The following tokens are operators:

[format="csv",width="60%",cols="15"]
[frame="topbot",grid="none"]
|=====
||,&&,==,!=,<,>,<=,>=,+,-,*,/,%,~,&
|=====


