== Expressions with Side Effects

Beside pure expressions, ABS has expressions with side effects. However, these expressions are defined in such a way that they can only have a single side effect. This means that subexpressions of expressions can only be pure expressions again. This restriction simplifies the reasoning about ABS expressions.

.New Expression

A New Expression creates a new object from a class name and a list of arguments. In ABS objects
can be created in two different ways. Either they are created in the current COG, using the standard
new local expression, or they are created in a new COG by using the new expression.

.Syntax

[source]
----
new local Foo(5)
new Bar()
----

Standard Object Creation

When using the new local expression, the new object is created in the current COG, i.e., the COG of the current receiver object.

.COG Object Creation

The concurrency model of ABS is based on the notion of COGs [?]. An ABS system at runtime is a set of concurrently running COGs. A COGs can be seen as an isolated subsystem, which has its own state (an object-heap) and its own internal behavior. COGs are created implicitly when creating a new object by using the new expression.

.Synchronous Call Expression
A Synchronous Call consists of a target expression, a method name, and a list of argument expressions.

[source]
----
Bool b = x.m(5);
----

.Asynchronous Call Expression
An Asynchronous Call consists of a target expression, a method name, and a list of argument expressions. Instead of directly invoking the method, an asynchronous method call creates a new task in the target COG, which is executed asynchronously. This means that the calling task proceeds independently after the call, without waiting for the result. The result of an asynchronous method call is a future (Fut<V>), which can be used by the calling task to later obtain the result of the method call. That future is resolved by the task that has been created in the target COG to execute the method.

[source, java]
----
Fut<Bool> f = x!m(5);
----

.Get Expression
A Get Expression is used to obtain the value from a future. The current task is blocked until the value of the future is available, i.e., until the future has been resolved. No other task in the COG can be activated in the meantime.

[source]
----
Bool b = f.get;
----

.Await Expression
A common pattern for asynchronous calls is:

* Execute an asynchronous call expression, store the future in a variable
* `await` on the future
* Assign the result to a variable

[source]
----
Fut<A> fx = o!m();
await fx?;
A x = fx.get;
----

The await expression is a shorthand for this pattern. The preceding example can be written as follows, without the need to introduce a name for the future:

[source]
----
A x = await o!m();
----
