== The ABS Language

The *ABS language* is an actor-based, object-oriented, executable modeling
language.  Its prime features are:

Algebraic user-defined data types and side effect-free functions :: All data
(except the state of objects and future variables) is immutable, and functions
are free of side effects.  This makes understanding and reasoning about models
easier.
+
User-defined data types are used for data modeling instead of objects, so ABS
models are typically smaller than their Java counterparts.

A syntax that is close to Java :: Programmers that are used to Java can easily
learn the ABS language.

Distributed, actor-based semantics :: Method calls are asynchronous and create
a new process in the target.  Processes are scheduled cooperatively and run
within the scope of one object.  Futures are used to synchronize with and get
the result of another process.

Interfaces for specifying object behavior :: Similar to Java, the behavior of
a class is defined by implementing zero or more interfaces with their
corresponding methods.

Safe concurrency :: Processes run cooperatively within one object and do not
have access to other objects' state, and data structures are immutable.  The
most common error causes of concurrent systems (aliasing, insufficient
locking) are avoided by the language semantics.

Distributed computing :: The combination of asynchronous method calls,
immutability and strong encapsulation makes it very easy to model distributed
systems.

A formal semantics and compositional proof theory :: ABS is designed to be
amenable to program analysis and verification.  A variety of tools (deadlock
checker, resource analysis, formal verification) have been developed.

.Non-goals
****
Languages are eco-systems, and a language containing all possible features
will be easy to use for no one.  The following areas are currently
under-served by ABS:

Parallel computing :: Algorithms relying on multiple processes operating on
mutable state, e.g., from the domain of scientific computing, can only be
expressed in roundabout ways.

Close-to-the-metal programming :: ABS is not designed to be a systems
programming language.
****


